export const SETTINGS = [
  "Fantasy",
  "Historical",
  "Post-apocalyptic",
  "Sci-fi",
  "Cyberpunk",
  "Horror",
  "Superhero",
  "Western",
  "Steampunk",
  "Survival",
  "Space",
  "Futuristic",
  "Mythological",
  "Zombie",
  "Martial arts",
  "Pirate",
  "Detective/Mystery",
  "Modern day",
  "War",
];

export const TONES = [
  "Serious",
  "Humorous",
  "Dark",
  "Suspenseful",
  "Action-packed",
  "Lighthearted",
  "Nostalgic",
  "Horror-filled",
  "Romantic",
  "Epic",
  "Whimsical",
  "Intense",
  "Optimistic",
  "Pessimistic",
  "Mysterious",
  "Satirical",
  "Comical",
  "Thought-provoking",
  "Bleak",
  "Tense",
];

export const OBJECTIVES = [
  "Survival",
  "Exploration",
  "Combat",
  "Building/Crafting",
  "Resource management",
  "Puzzle solving",
  "Story progression",
  "Gathering/Collecting items",
  "Character development",
  "Quest completion",
  "World domination/conquest",
  "Escaping/Surviving a situation",
  "Thief/Stealing objectives",
  "Level progression",
  "Defending/Protecting",
  "Trading/Negotiating",
  "Stealth",
  "Racing/Chasing",
];

export const DETAILS = [
  "Alien races",
  "Magic spells",
  "Medieval knights",
  "Post-apocalyptic wasteland",
  "Cybernetic implants",
  "Monstrous creatures",
  "Superpowered heroes",
  "Wild west gunslingers",
  "Steampunk machines",
  "Stranded survival",
  "Intergalactic travel",
  "High-tech future",
  "Legendary gods",
  "Undead horde",
  "Martial arts master",
  "Pirate treasure",
  "Crime investigation",
  "Modern city life",
  "War-torn battlefield",
];
